### PR TITLE
Refactored item list

### PR DESCRIPTION
**Pull request by enriquemorenotent**
I refactored a little your components.

You should make components that are smaller, and make just one thing. ;)

### CODE REVIEW

**Comment by peschina** [comment]
Thanks a lot for the PR @enriquemorenotent!! 
I tested your code locally and I saw that there is an error in the console, it seems like the key property is missing in the items returned by the map method in the toDoList component. Could you please fix it?

I also wrote a couple of lines to push new items to the end of the list (I thought that it would be better to have on top of the list the tasks that haven't been completed yet, so that they are more easily trackable). Is there any reason why you removed it?

Many thanks again! :)

**Comment by enriquemorenotent** [comment]
You are welcome. Happy to give you my feedback.

You are right. I forgot the key, so I corrected it. It should give you no warning anymore.

I am not sure what do you mean on the second paragraph, though. You say that when you add an item, it appears on the end of the list? I have cloned your repo and tried this, but the items keep appearing *at the beginning* of the list. Am I misunderstanding you?

**Comment by peschina** [comment]
I'm sorry for the misunderstanding, it was my mistake: I meant to write something different. 
I wanted to always have on top of the list all items that haven't been completed yet. New items appear at the beginning of the list, and it's the intended behavior. But I also wanted to push all completed items to the end of the list, so I wrote a couple of lines for that in the toggleCompleted method. I attach it here so you can have a quick look:

`toggleCompleted = id => {
		const { toDoItems } = this.state;
	    let list = toDoItems.map(item => {
	     if (item.id == id) item.completed = true;
	      return item;
	    });
	    // Push item to end of array
		const item = toDoItems.filter(i => i.id == id);
		list = [...toDoItems.filter(i => i.id !== id), ...item];
	    this.setState({ toDoItems: list });
	  };`

I just wanted to know if there is something wrong with the implementation or if you thought that we could just do without it.
Thanks a lot!

**Comment by enriquemorenotent** [comment]
I did not notice that feature! I have corrected it :smile: 

One big red flag I noticed immediately in the code was this:

```js
class ToDoList extends ToDoListForm {
```

Class inheritance, while useful in some cases, it is hard to maintain. It is specially evil with Javascript, which works better as a functional language. And it is SPECIALLY evil with React. If you see yourself extending a class that is not `React.Component`, it is a good idea to reassess if your code is well designed.

One advice to avoid this kind of problem: Write as often as you can functional components. This means favoring...

```js
const ToDoList = props => { ... }
```
...over...

```js
class ToDoList extends React.Component
```

**Comment by peschina** [comment]
Thanks!!! Your advice is really is really helpful! 
I actually had a much longer (and messy) toDoList component in the beginning, and tried to refactor it to make it simpler. Now I definitely see that just splitting it into smaller components would have done the trick.
I also saw that you used hooks in your code, and this has been a great opportunity to take a good look at the documentation and try them out :)

**Comment by enriquemorenotent** [comment]
Hooks are great. Allows for more functional code. Besides, not using classes makes JS more enjoyable, after a while. Using `this` in JS will just give you headaches in the long run.

Once you merge the code, I will take a look at the other half of the app, and give you my feedback.

**Comment by peschina** [comment]
Thanks Enrique! :)

**Pull request merged**
